---
- name: test
  shell: echo {{pnotes_dir}}/hello

- name: 'Copy client.json to pnotes'
  local_action: template src=../playbooks/roles/v2ray/templates/client-config.json.j2 dest="{{pnotes_dir}}/source/_vpns/v2ray/{{inventory_hostname}}.json"

- name: 'Deploy pnotes'
  local_action: shell cd {{pnotes_dir}} && ./ake deploy